[
  {
    Class_Type: "Online",
    Exam_Score_1: "65",
    Exam_Score_2: "68",
    Student: "1",
    Study_Hours: "1-2 hours",
    Teaching_Method: "A",
  },
  {
    Class_Type: "Online",
    Exam_Score_1: "70",
    Exam_Score_2: "72",
    Student: "2",
    Study_Hours: "1-2 hours",
    Teaching_Method: "A",
  },
  {
    Class_Type: "Online",
    Exam_Score_1: "78",
    Exam_Score_2: "80",
    Student: "3",
    Study_Hours: "3-4 hours",
    Teaching_Method: "A",
  },
  {
    Class_Type: "In-person",
    Exam_Score_1: "85",
    Exam_Score_2: "87",
    Student: "4",
    Study_Hours: "3-4 hours",
    Teaching_Method: "A",
  },
  {
    Class_Type: "Online",
    Exam_Score_1: "72",
    Exam_Score_2: "74",
    Student: "5",
    Study_Hours: "1-2 hours",
    Teaching_Method: "B",
  },
  {
    Class_Type: "Online",
    Exam_Score_1: "75",
    Exam_Score_2: "77",
    Student: "6",
    Study_Hours: "1-2 hours",
    Teaching_Method: "B",
  },
  {
    Class_Type: "In-person",
    Exam_Score_1: "88",
    Exam_Score_2: "90",
    Student: "7",
    Study_Hours: "3-4 hours",
    Teaching_Method: "B",
  },
  {
    Class_Type: "In-person",
    Exam_Score_1: "92",
    Exam_Score_2: "94",
    Student: "8",
    Study_Hours: "3-4 hours",
    Teaching_Method: "B",
  },
  {
    Class_Type: "Online",
    Exam_Score_1: "68",
    Exam_Score_2: "70",
    Student: "9",
    Study_Hours: "1-2 hours",
    Teaching_Method: "C",
  },
  {
    Class_Type: "Online",
    Exam_Score_1: "72",
    Exam_Score_2: "74",
    Student: "10",
    Study_Hours: "1-2 hours",
    Teaching_Method: "C",
  },
  {
    Class_Type: "In-person",
    Exam_Score_1: "75",
    Exam_Score_2: "78",
    Student: "11",
    Study_Hours: "3-4 hours",
    Teaching_Method: "C",
  },
  {
    Class_Type: "In-person",
    Exam_Score_1: "82",
    Exam_Score_2: "85",
    Student: "12",
    Study_Hours: "3-4 hours",
    Teaching_Method: "C",
  },
];
